[tools]
chezmoi = "latest"
node = "latest"
"npm:@aku11i/phantom" = "latest"
"npm:@openai/codex" = "latest"
"npm:@shopify/cli" = "latest"
"npm:agent-browser" = "latest"
"npm:eas-cli" = "latest"
"npm:repomix" = "latest"
"npm:takt" = "latest"
pnpm = "10.28"
zellij = "latest"

[tasks.pf]
description = "SSH port-forward in background (ask interactively)"
run = "~/.config/mise/scripts/pf-start.sh"

[tasks."pf:list"]
description = "List active SSH port-forwards"
run = "~/.config/mise/scripts/pf-list.sh"

[tasks."pf:stop"]
description = "Stop SSH port-forward interactively"
run = "~/.config/mise/scripts/pf-stop.sh"

[tasks.site2skill]
description = "Convert website to Codex skill interactively"
run = "~/.config/mise/scripts/site2skill.sh"

[tasks.format]
description = "Run custom formatting script interactively"
run = "~/.config/mise/scripts/format.sh"

[tasks.fcitx5:restart]
description = "Restart fcitx5 demon"
run ="fcitx5 -r -d"
